### ISSUE TITLE
cannot convert from mysql to yaml

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/QuestsConverter#1]
Quests-4.6.0#361
QuestsConverter-0.3

using command 
qconvert playerdata mysql yaml

it show 
![image](https://github.com/PikaMug/QuestsConverter/assets/61608872/47d65e7d-02fb-4b4c-89e8-98b1f3b84dd9)

but no data folder, or data file is created

quests config
https://paste.denizenscript.com/View/109692

server log:
https://paste.denizenscript.com/View/109693

**Comment by PikaMug** [comment]
Thanks for the report. I see your Quests version is outdated. Please check whether this still occurs with the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/412/

**Comment by hkkongou** [comment]
> Thanks for the report. I see your Quests version is outdated. Please check whether this still occurs with the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/412/

hi, i just used Quests-4.8.2#412, but the result is the same, what should i do

**Comment by PikaMug** [comment]
Is your MySQL server running (and your Quests config values correct)? It seems as if there's no SQL data found to convert.

**Comment by hkkongou** [comment]
> Is your MySQL server running (and your Quests config values correct)? It seems as if there's no SQL data found to convert.

it will say error if i got the mysql server offline or password incorrect. I see no errors there then i assume the mysql connection and set up is correct

**Comment by PikaMug** [comment]
@hkkongou Try this build and let me know what console output you get:
https://www.dropbox.com/s/2q673zc0rnj36mt/QuestsConverter-0.3a.jar?dl=0

**Comment by hkkongou** [comment]
> @hkkongou Try this build and let me know what console output you get: https://www.dropbox.com/s/2q673zc0rnj36mt/QuestsConverter-0.3a.jar?dl=0

you are right, i got the table_prefix wrong, now the 3a version told me the thing and i changed it, works now 👍
